services:
  nuxt:
    image: ${DOCKER_REGISTRY:-registry.budhapp.com}/${PROJECT_NAME}-nuxt:${TAG:-latest}
    container_name: ${PROJECT_NAME}-nuxt
    build:
      context: ./nuxt
      target: ${DOCKER_TARGET:-production}
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./nuxt:/app
      - /app/node_modules
      - /app/.nuxt
    depends_on:
      - api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GO_API_URL=${GO_API_URL:-http://${PROJECT_NAME}-api:8080}
      - PAYMENT_PROVIDER=${PAYMENT_PROVIDER}
      - POLAR_ACCESS_TOKEN=${POLAR_ACCESS_TOKEN}
      - POLAR_SERVER=${POLAR_SERVER}
      - POLAR_SUCCESS_URL=${POLAR_SUCCESS_URL}

  api:
    image: ${DOCKER_REGISTRY:-registry.budhapp.com}/${PROJECT_NAME}-api:${TAG:-latest}
    container_name: ${PROJECT_NAME}-api
    build:
      context: ./api
      target: ${DOCKER_TARGET:-production}
      dockerfile: Dockerfile
      args:
        TARGETOS: ${TARGETOS:-linux}
        TARGETARCH: ${TARGETARCH:-amd64}
    platform: ${PLATFORM:-linux}/${TARGETARCH:-amd64}
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - PAYMENT_PROVIDER=${PAYMENT_PROVIDER}
      - POLAR_ACCESS_TOKEN=${POLAR_ACCESS_TOKEN}
    volumes:
      - ./api:/app
      - ./data/shared:/data/shared
    ports:
      - 8080:8080


  svelt:
    image: ${DOCKER_REGISTRY:-registry.budhapp.com}/${PROJECT_NAME}-svelt:${TAG:-latest}
    container_name: ${PROJECT_NAME}-svelt
    build:
      context: ./svelt
      target: ${DOCKER_TARGET:-production}
      dockerfile: Dockerfile
    ports:
      - 3001:5173
    volumes:
      - ./svelt:/app
      - /app/node_modules
      - /app/.nuxt
    depends_on:
      - api
    environment:
      - ORIGIN=${DOMAIN_URL:-http://localhost:3001}
      - DATABASE_URL=${DATABASE_URL}
      - GO_API_URL=${GO_API_URL:-http://${PROJECT_NAME}-api:8080}
      - PAYMENT_PROVIDER=${PAYMENT_PROVIDER}
      - POLAR_ACCESS_TOKEN=${POLAR_ACCESS_TOKEN}
      - POLAR_SERVER=${POLAR_SERVER}
      - POLAR_SUCCESS_URL=${POLAR_SUCCESS_URL}
